name: Log Click

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log the click
        run: |
          echo "Click at $(date -u)" >> clicks.txt

      - name: Commit and push
        run: |
          git config user.name "ClickBot"
          git config user.email "bot@clicktracker.com"
          git add clicks.txt
          git commit -m "Logged click" || echo "No changes"
          git push
